language: go

go:
  - "1.9.x"
  - tip

before_install:
  - go get -t -v ./...

script:
  - go get -u golang.org/x/lint/golint
  - $GOPATH/bin/golint -set_exit_status .
  - go test
    #  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod


